### ISSUE TITLE
_context->getBroadcastTransport() -> NULL

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvAccessCPP#39]
I've seen this crash a couple of times now immediately when my PVA server starts up.  Doesn't happen every time, and so far not when run from gdb (below is from core file).  So far it has only happened when some PVA client was already searching, so maybe some race?

The exact revision in question is de0f26f87ee333967ef8b8705b219e398b2b4484 on https://github.com/mdavidsaver/pvAccessCPP/tree/pva2pva, though I don't think there are relevant changes.

```
#0  0x00007f123badd832 in epics::pvAccess::ServerChannelFindRequesterImpl::channelFindResult (
    this=0x7f11ec0008f0, channelFind=std::tr1::shared_ptr (count 1, weak 0) 0x7f11ec000a90, wasFound=true)
    at ../../src/server/responseHandlers.cpp:412
#1  0x00007f123be6cac5 in PDBProvider::channelFind (this=0x8971b0, channelName="cnt:x", 
    requester=std::tr1::shared_ptr (count 3, weak 1) 0x7f11ec0008f0) at ../pdb.cpp:482
#2  0x00007f123badcf39 in epics::pvAccess::ServerSearchHandler::handleResponse (this=0x8adac0, 
    responseFrom=0x7f1231e4cd90, transport=std::tr1::shared_ptr (count 2, weak 1) 0x911960, version=1 '\001', 
    command=3 '\003', payloadSize=43, payloadBuffer=0x911b10) at ../../src/server/responseHandlers.cpp:316
#3  0x00007f123badc502 in epics::pvAccess::ServerResponseHandler::handleResponse (this=0x8974f0, 
    responseFrom=0x7f1231e4cd90, transport=std::tr1::shared_ptr (count 2, weak 1) 0x911960, version=1 '\001', 
    command=3 '\003', payloadSize=43, payloadBuffer=0x911b10) at ../../src/server/responseHandlers.cpp:148
#4  0x00007f123ba75d0a in epics::pvAccess::BlockingUDPTransport::processBuffer (this=0x911960, 
    transport=std::tr1::shared_ptr (count 2, weak 1) 0x911960, fromAddress=..., receiveBuffer=0x911b10)
    at ../../src/remote/blockingUDPTransport.cpp:398
#5  0x00007f123ba757da in epics::pvAccess::BlockingUDPTransport::run (this=0x911960)
    at ../../src/remote/blockingUDPTransport.cpp:255
#6  0x00007f123aa79f88 in epicsThreadCallEntryPoint (pPvt=0x932180) at ../../../src/libCom/osi/epicsThread.cpp:85
#7  0x00007f123aa8269a in start_routine (arg=0x9322e0) at ../../../src/libCom/osi/os/posix/osdThread.c:403
#8  0x00007f1239c4e0a4 in start_thread (arg=0x7f1231e4d700) at pthread_create.c:309
#9  0x00007f1239f4b87d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) f
#0  0x00007f123badd832 in epics::pvAccess::ServerChannelFindRequesterImpl::channelFindResult (
    this=0x7f11ec0008f0, channelFind=std::tr1::shared_ptr (count 1, weak 0) 0x7f11ec000a90, wasFound=true)
    at ../../src/server/responseHandlers.cpp:412
412             _context->getBroadcastTransport()->enqueueSendRequest(thisSender);
(gdb) info args
this = 0x7f11ec0008f0
channelFind = std::tr1::shared_ptr (count 1, weak 0) 0x7f11ec000a90
wasFound = true
(gdb) info loc
thisSender = std::tr1::shared_ptr (count 3, weak 1) 0x7f11ec0008f8
guard = {<epics::pvData::NoDefaultMethods> = {<No data fields>}, mutexPtr = @0x7f11ec0009c8, locked = true}
(gdb) p _context
$7 = std::tr1::shared_ptr (count 22, weak 1) 0x896980
(gdb) p _context._M_ptr->_broadcastTransport 
$8 = std::tr1::shared_ptr (empty) 0x0
(gdb) p *_context._M_ptr
$9 = {<epics::pvAccess::ServerContext> = {
    _vptr.ServerContext = 0x7f123bdd72d0 <vtable for epics::pvAccess::ServerContextImpl+16>}, <epics::pvAccess::Context> = {
    _vptr.Context = 0x7f123bdd7380 <vtable for epics::pvAccess::ServerContextImpl+192>}, <std::tr1::enable_shared_from_this<epics::pvAccess::ServerContextImpl>> = {
    _M_weak_this = std::tr1::weak_ptr (count 22, weak 1) 0x896980}, 
  static VERSION = {<epics::pvData::NoDefaultMethods> = {<No data fields>}, _productName = "pvAccess Server", 
    _implementationLanguage = "cpp", _majorVersion = 4, _minorVersion = 2, _maintenanceVersion = 0, 
    _developmentFlag = true}, static StateNames = {0x7f123bb56a5a "NOT_INITIALIZED", 
    0x7f123bb56a6a "INITIALIZED", 0x7f123bb56a76 "RUNNING", 0x7f123bb56a7e "SHUTDOWN", 
    0x7f123bb56a87 "DESTROYED"}, _guid = {value = "\275\275\362V\000\000\000\000U3\331\a"}, 
  _state = epics::pvAccess::ServerContextImpl::NOT_INITIALIZED, _beaconAddressList = "", 
  _ifaceList = std::vector of length 4, capacity 4 = {{ifaceAddr = {ia = {sin_family = 4099, sin_port = 0, 
          sin_addr = {s_addr = 16975114}, sin_zero = "\000\000\000\000\000\000\000"}, sa = {sa_family = 4099, 
          sa_data = "\000\000\n\005\003\001\000\000\000\000\000\000\000"}}, ifaceBCast = {ia = {sin_family = 2, 
          sin_port = 0, sin_addr = {s_addr = 4278387978}, sin_zero = "\000\000\000\000\000\000\000"}, sa = {
          sa_family = 2, sa_data = "\000\000\n\005\003\377\000\000\000\000\000\000\000"}}}, {ifaceAddr = {ia = {
          sin_family = 4163, sin_port = 0, sin_addr = {s_addr = 3355508746}, 
          sin_zero = "\000\000\000\000\000\000\000"}, sa = {sa_family = 4163, 
          sa_data = "\000\000\n\000\001\310\000\000\000\000\000\000\000"}}, ifaceBCast = {ia = {sin_family = 2, 
          sin_port = 0, sin_addr = {s_addr = 4278255626}, sin_zero = "\000\000\000\000\000\000\000"}, sa = {
          sa_family = 2, sa_data = "\000\000\n\000\001\377\000\000\000\000\000\000\000"}}}, {ifaceAddr = {ia = {
          sin_family = 4163, sin_port = 0, sin_addr = {s_addr = 16844042}, 
          sin_zero = "\000\000\000\000\000\000\000"}, sa = {sa_family = 4163, 
          sa_data = "\000\000\n\005\001\001\000\000\000\000\000\000\000"}}, ifaceBCast = {ia = {sin_family = 2, 
          sin_port = 0, sin_addr = {s_addr = 4278256906}, sin_zero = "\000\000\000\000\000\000\000"}, sa = {
          sa_family = 2, sa_data = "\000\000\n\005\001\377\000\000\000\000\000\000\000"}}}, {ifaceAddr = {ia = {
          sin_family = 4099, sin_port = 0, sin_addr = {s_addr = 16909578}, 
          sin_zero = "\000\000\000\000\000\000\000"}, sa = {sa_family = 4099, 
          sa_data = "\000\000\n\005\002\001\000\000\000\000\000\000\000"}}, ifaceBCast = {ia = {sin_family = 2, 
          sin_port = 0, sin_addr = {s_addr = 4278322442}, sin_zero = "\000\000\000\000\000\000\000"}, sa = {
          sa_family = 2, sa_data = "\000\000\n\005\002\377\000\000\000\000\000\000\000"}}}}, _ifaceAddr = {ia = {
      sin_family = 2, sin_port = 54035, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, 
    sa = {sa_family = 2, sa_data = "\023\323", '\000' <repeats 11 times>}}, _ignoreAddressList = "", 
  _autoBeaconAddressList = true, _beaconPeriod = 15, _broadcastPort = 5076, _serverPort = 5075, 
  _receiveBufferSize = 16384, _timer = std::tr1::shared_ptr (count 1, weak 0) 0x897720, 
  _udpTransports = std::vector of length 6, capacity 8 = {std::tr1::shared_ptr (count 2, weak 1) 0x8aeb10, 
    std::tr1::shared_ptr (count 2, weak 1) 0x8d08f0, std::tr1::shared_ptr (count 2, weak 1) 0x8f1570, 
    std::tr1::shared_ptr (count 2, weak 1) 0x911960, std::tr1::shared_ptr (count 2, weak 1) 0x932530, 
    std::tr1::shared_ptr (count 2, weak 1) 0x952960}, _broadcastTransport = std::tr1::shared_ptr (empty) 0x0, 
  _beaconEmitter = std::tr1::shared_ptr (empty) 0x0, 
  _acceptor = std::tr1::shared_ptr (count 1, weak 0) 0x8ae610, 
  _transportRegistry = std::tr1::shared_ptr (count 1, weak 0) 0x8973a0, 
  _responseHandler = std::tr1::shared_ptr (count 10, weak 0) 0x8974f0, 
---Type <return> to continue, or q <return> to quit---
  _channelProviderRegistry = std::tr1::shared_ptr (count 3, weak 0) 0x896fc0, _channelProviderNames = "QSRV", 
  _channelProviders = std::vector of length 1, capacity 1 = {std::tr1::shared_ptr (count 3, weak 4) 0x8971b0}, 
  _mutex = {id = 0x896b30}, _runEvent = {id = 0x896b60}, 
  _beaconServerStatusProvider = std::tr1::shared_ptr (empty) 0x0, 
  configuration = std::tr1::shared_ptr (count 2, weak 0) 0x896de0, _startTime = {secPastEpoch = 827596861, 
    nsec = 131664458}}
```

**Comment by msekoranja** [comment]
Wrong UDP transport initialization order (or missing null check). 
I will fix in the evening.
